name: Relese Packages
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: release please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          command: manifest
          config-file: .github/release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > .npmrc

      - name: install dependencies
        run: pnpm install

      - name: release packages
        run: pnpm -r publish --no-git-checks
